TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
DB += common.db
DB += bend.db
DB += family.db
DB += family.substitutions
DB += individual.db
DB += kickers.db
DB += ch.substitutions
DB += cv.substitutions
DB += fch.substitutions
DB += fcv.substitutions
DB += qs.substitutions
DB += qda.substitutions
DB += qfa.substitutions
DB += qfb.substitutions
DB += qdb1.substitutions
DB += qdb2.substitutions
DB += qfp.substitutions
DB += qdp1.substitutions
DB += qdp2.substitutions
DB += q1.substitutions
DB += q2.substitutions
DB += q3.substitutions
DB += q4.substitutions
DB += sda0.substitutions
DB += sda1.substitutions
DB += sda2.substitutions
DB += sda3.substitutions
DB += sfa0.substitutions
DB += sfa1.substitutions
DB += sfa2.substitutions
DB += sdb0.substitutions
DB += sdb1.substitutions
DB += sdb2.substitutions
DB += sdb3.substitutions
DB += sfb0.substitutions
DB += sfb1.substitutions
DB += sfb2.substitutions
DB += sdp0.substitutions
DB += sdp1.substitutions
DB += sdp2.substitutions
DB += sdp3.substitutions
DB += sfp0.substitutions
DB += sfp1.substitutions
DB += sfp2.substitutions
DB += kickers.substitutions

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
