TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
DB += common.db
DB += family.db
DB += family.substitutions
DB += individual.db
DB += chs.substitutions
DB += cvs.substitutions
DB += qda.substitutions
DB += qdb1.substitutions
DB += qdb2.substitutions
DB += qf1.substitutions
DB += qf2.substitutions
DB += qf3.substitutions
DB += qf4.substitutions
DB += qfa.substitutions
DB += qfb.substitutions
DB += qs.substitutions
DB += sd1.substitutions
DB += sd2.substitutions
DB += sd3.substitutions
DB += sd4.substitutions
DB += sd5.substitutions
DB += sd6.substitutions
DB += sda.substitutions
DB += sdb.substitutions
DB += sf1.substitutions
DB += sf2.substitutions
DB += sf3.substitutions
DB += sf4.substitutions
DB += sfa.substitutions
DB += sfb.substitutions

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
