TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
DB += common.db
DB += family.db
DB += family.substitutions
DB += individual.db
DB += ch.substitutions
DB += cv.substitutions
DB += fch.substitutions
DB += fcv.substitutions
DB += qda.substitutions
DB += qdb1.substitutions
DB += qdb2.substitutions
DB += qf1.substitutions
DB += qf2.substitutions
DB += qf3.substitutions
DB += qf4.substitutions
DB += qfa.substitutions
DB += qfb.substitutions
DB += qs.substitutions
DB += sd1j.substitutions
DB += sd2j.substitutions
DB += sd3j.substitutions
DB += sd1k.substitutions
DB += sd2k.substitutions
DB += sd3k.substitutions
DB += sda.substitutions
DB += sdb.substitutions
DB += sf1j.substitutions
DB += sf2j.substitutions
DB += sf1k.substitutions
DB += sf2k.substitutions
DB += sfa.substitutions
DB += sfb.substitutions

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
